
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JTextField;
import javax.xml.parsers.SAXParser;
import org.w3c.dom.NodeList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author xp
 */


public class MiFrame extends javax.swing.JFrame {
    
     DOM gesDOM = new DOM();
     SAX gessAX = new SAX();
     JAXB gesJAXB = new JAXB();
     File archivoSeleccionado;
     String nuevoTitulo;
     String nuevoAutor;
             String nuevaPublicacion;
             File fXML;
             SAXParser parser;
             ManejadorSAX sh;
             
             
    
    
    /**
     * Creates new form MiFrame
     */
    public MiFrame() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        titulo = new javax.swing.JLabel();
        autor = new javax.swing.JLabel();
        publicaccion = new javax.swing.JLabel();
        guardar = new javax.swing.JButton();
        mostrarcontenido = new javax.swing.JButton();
        mostrarSAX = new javax.swing.JButton();
        mostrarJAXB = new javax.swing.JButton();
        descripciontitulo = new javax.swing.JTextField();
        descripcionAutor = new javax.swing.JTextField();
        anopublicacion = new javax.swing.JTextField();
        annadir = new javax.swing.JButton();
        ficheronoseleccionado = new javax.swing.JLabel();
        descripcionantiguiotitulo = new javax.swing.JTextField();
        nuevotitulo = new javax.swing.JTextField();
        antiguotitutlo = new javax.swing.JLabel();
        tituloacambiar = new javax.swing.JLabel();
        cambiartitulo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        errores = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        domitem = new javax.swing.JMenuItem();
        saxitem = new javax.swing.JMenuItem();
        jaxbitem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        titulo.setText("Titulo");

        autor.setText("Autor");

        publicaccion.setText("Publicado en ");

        guardar.setText("Guardar DOM como salida XML");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        mostrarcontenido.setText("Mostrar contenido DOM");
        mostrarcontenido.setEnabled(false);
        mostrarcontenido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarcontenidoActionPerformed(evt);
            }
        });

        mostrarSAX.setText("Mostrar contenido SAX");
        mostrarSAX.setEnabled(false);
        mostrarSAX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarSAXActionPerformed(evt);
            }
        });

        mostrarJAXB.setText("Mostrar contenido JAXB");
        mostrarJAXB.setEnabled(false);
        mostrarJAXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarJAXBActionPerformed(evt);
            }
        });

        annadir.setText("AÒadir");
        annadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annadirActionPerformed(evt);
            }
        });

        ficheronoseleccionado.setText("<fichero no seleccionado>");

        antiguotitutlo.setText("Titulo");

        tituloacambiar.setText("tituloNuevo");

        cambiartitulo.setText("Cambiar Titulo");
        cambiartitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiartituloActionPerformed(evt);
            }
        });

        jLabel7.setText("Titulo a Cambiar ");

        jMenu1.setText("Ficheros XML");

        domitem.setText("DOM");
        domitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                domitemActionPerformed(evt);
            }
        });
        jMenu1.add(domitem);

        saxitem.setText("SAX");
        saxitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saxitemActionPerformed(evt);
            }
        });
        jMenu1.add(saxitem);

        jaxbitem.setText("JAXB");
        jaxbitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaxbitemActionPerformed(evt);
            }
        });
        jMenu1.add(jaxbitem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mostrarcontenido, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(mostrarSAX, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mostrarJAXB, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(autor)
                                    .addComponent(titulo)
                                    .addComponent(publicaccion))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(descripciontitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(descripcionAutor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(anopublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(44, 44, 44)
                                        .addComponent(annadir))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tituloacambiar)
                                            .addComponent(antiguotitutlo))
                                        .addGap(49, 49, 49)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(descripcionantiguiotitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nuevotitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(26, 26, 26))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(cambiartitulo)
                                                .addGap(110, 110, 110)))))))))
                .addGap(38, 38, 38))
            .addComponent(ficheronoseleccionado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(errores, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(ficheronoseleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mostrarcontenido)
                    .addComponent(mostrarSAX)
                    .addComponent(mostrarJAXB))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(errores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(titulo)
                            .addComponent(descripciontitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(autor)
                            .addComponent(descripcionAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(publicaccion)
                            .addComponent(anopublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(annadir))
                        .addGap(32, 32, 32)
                        .addComponent(guardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(antiguotitutlo)
                                .addGap(41, 41, 41)
                                .addComponent(tituloacambiar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(descripcionantiguiotitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(nuevotitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(cambiartitulo)))
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        gesDOM.guardarDOMcomoFILE();
    }//GEN-LAST:event_guardarActionPerformed

    private void domitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_domitemActionPerformed
            JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File("C:\\Users\\xp\\Documents"));
        int retrival = chooser.showSaveDialog(null);
        if (retrival == JFileChooser.APPROVE_OPTION) {
               archivoSeleccionado = chooser.getSelectedFile();
                gesDOM.abrir_XML_DOM(archivoSeleccionado);
        if( gesDOM.abrir_XML_DOM(archivoSeleccionado) == 0){
                mostrarcontenido.setEnabled(true);
            }
        }
        ficheronoseleccionado.setText("has seleccionado un fichero");
    }//GEN-LAST:event_domitemActionPerformed

    private void mostrarcontenidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarcontenidoActionPerformed
        // TODO add your handling code here:
       jTextArea1.setText(gesDOM.recorrerDOMyMostrar(gesDOM.doc));
       ficheronoseleccionado.setText("vas a mostrar un fichero");
        
    }//GEN-LAST:event_mostrarcontenidoActionPerformed

    private void annadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annadirActionPerformed
          nuevoTitulo = descripciontitulo.getText();
       nuevoAutor = descripcionAutor.getText();
       nuevaPublicacion = anopublicacion.getText();
        gesDOM.annadirDOM( nuevoTitulo, nuevoAutor, nuevaPublicacion);
        guardar.setEnabled(true);
       ficheronoseleccionado.setText("has a√±adido algo");

        
    }//GEN-LAST:event_annadirActionPerformed

    private void cambiartituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiartituloActionPerformed
        //variable booleana para saber si te han encontrado el titulo o no 
        boolean encontrado = true;
      
                //encontrado es igual al funcion cambiartitulo y obtiene lo escrito en el jtexfield4 , jtextfield5
          encontrado = gesDOM.cambiarTitulo(descripcionantiguiotitulo.getText(), nuevotitulo.getText());
        jTextArea1.setText(gesDOM.recorrerDOMyMostrar(gesDOM.doc)); 
       
        if(encontrado){
             errores.setText("titulo cambiado");
           
        }else{
            errores.setText("no existe el titulo");
            
        }
        
    }//GEN-LAST:event_cambiartituloActionPerformed

    private void jaxbitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaxbitemActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File("C:\\Users\\xp\\Documents"));
        int retrival = chooser.showSaveDialog(null);
        if (retrival == JFileChooser.APPROVE_OPTION) {
               archivoSeleccionado = chooser.getSelectedFile();
                gesJAXB.abrir_XML_JAXB(archivoSeleccionado);
        if( gesJAXB.abrir_XML_JAXB(archivoSeleccionado) == 0){
                mostrarJAXB.setEnabled(true);
            }
        }
        ficheronoseleccionado.setText("has seleccionado un fichero");
    }//GEN-LAST:event_jaxbitemActionPerformed

    private void mostrarJAXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarJAXBActionPerformed
      jTextArea1.setText(gesJAXB.recorrerJAXByMostrar());
    }//GEN-LAST:event_mostrarJAXBActionPerformed

    private void mostrarSAXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarSAXActionPerformed
        jTextArea1.setText(gessAX.recorrerSAX( ));
    }//GEN-LAST:event_mostrarSAXActionPerformed

    private void saxitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saxitemActionPerformed
          JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File("C:\\Users\\xp\\Documents"));
        int retrival = chooser.showSaveDialog(null);
        if (retrival == JFileChooser.APPROVE_OPTION) {
               archivoSeleccionado = chooser.getSelectedFile();
                gessAX.abrir_XML_SAX(archivoSeleccionado);
        if( gessAX.abrir_XML_SAX(archivoSeleccionado) == 0){
                mostrarSAX.setEnabled(true);
            }
        }
        ficheronoseleccionado.setText("has seleccionado un fichero");
    }//GEN-LAST:event_saxitemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MiFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annadir;
    private javax.swing.JTextField anopublicacion;
    private javax.swing.JLabel antiguotitutlo;
    private javax.swing.JLabel autor;
    private javax.swing.JButton cambiartitulo;
    private javax.swing.JTextField descripcionAutor;
    private javax.swing.JTextField descripcionantiguiotitulo;
    private javax.swing.JTextField descripciontitulo;
    private javax.swing.JMenuItem domitem;
    private javax.swing.JLabel errores;
    private javax.swing.JLabel ficheronoseleccionado;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JMenuItem jaxbitem;
    private javax.swing.JButton mostrarJAXB;
    private javax.swing.JButton mostrarSAX;
    private javax.swing.JButton mostrarcontenido;
    private javax.swing.JTextField nuevotitulo;
    private javax.swing.JLabel publicaccion;
    private javax.swing.JMenuItem saxitem;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel tituloacambiar;
    // End of variables declaration//GEN-END:variables
}
